# Nash Social Welfare 最大化実装

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(data={"リンゴ": [0.8, 0.2, 0.3], "バナナ": [0.1, 0.0, 0.0], "イチゴ": [0.1, 0.9, 0.8]}, index=["父","母","子"])
df

リンゴ  バナナ  イチゴ
父  0.8  0.1  0.1
母  0.2  0.0  0.9
子  0.3  0.0  0.8

In [3]:
rui = df.to_numpy()

In [4]:
import itertools

elements = [0, 0.2, 0.5, 0.8, 1]  # 取り得る値のリスト
combinations = list(itertools.product(elements, repeat=9))  # 要素の全ての組み合わせを生成

valid_matrices = []  # 条件を満たす行列のリスト

# 全ての組み合わせについてチェック
for combination in combinations:
    matrix = np.array(combination).reshape((3, 3))  # 3x3の行列に変形
    if np.allclose(np.sum(matrix, axis=0), np.ones(3)):  # 列の合計が1になるかチェック
        valid_matrices.append(matrix)

print("Number of valid matrices:", len(valid_matrices))  

Number of valid matrices: 1728


In [6]:
prodMap = []
sumMap = []
for i, divide in enumerate(valid_matrices):
    prodMap.append(tuple((i ,np.prod(np.sum(divide*rui,axis=1)))))
    sumMap.append(tuple((i ,np.sum(np.sum(divide*rui,axis=1)))))

max_prod = sorted(prodMap, key=lambda x:x[1], reverse=True)[0]
max_sum = sorted(sumMap, key=lambda x:x[1], reverse=True)[0]

print(f'最大総積: {max_prod[1]:.2f}') 
print(valid_matrices[max_prod[0]])
print('---------------------------------------------------------------------')
print(f'最大総和: {max_sum[1]:.2f}')
print(valid_matrices[max_sum[0]])
print('---------------------------------------------------------------------')
print(rui)

最大総積: 0.16
[[1.  1.  0. ]
 [0.  0.  0.5]
 [0.  0.  0.5]]
---------------------------------------------------------------------
最大総和: 1.80
[[1 1 0]
 [0 0 1]
 [0 0 0]]
---------------------------------------------------------------------
[[0.8 0.1 0.1]
 [0.2 0.  0.9]
 [0.3 0.  0.8]]


# Fair Ranking as Fair Division: Impact-Based Individual Fairness in Ranking (KDD'22)

In [58]:
rui = np.random.rand(100,50)
exposure = [1.0, 0]

In [59]:
recommend = np.argsort(-rui)[:,:2]

In [61]:
imp_i = dict()
for user_index, item_list in enumerate(recommend):
    imp = rui[len(exposure)*[user_index],recommend[user_index]] * exposure
    for i in range(len(item_list)):
        item_index = item_list[i]
        imp_i[item_index] = imp[i] + imp_i.get(item_index, 0)
        