### k近傍法を用いた内容ベース推薦

In [1]:
import numpy as np
Du = np.array([
               [5, 3, +1],
               [6, 2, +1],
               [4, 1, +1],
               [8, 5, -1],
               [2, 4, -1],
               [3, 6, -1],
               [7, 6, -1],
               [4, 2, np.nan],
               [5, 1, np.nan],
               [8, 6, np.nan],
               [3, 4, np.nan],
               [4, 7, np.nan],
               [4, 4, np.nan],
])
I = np.arange(Du.shape[0])
x = Du[:,:-1]
Iu = I[~np.isnan(Du[:,-1])]
Iup = I[Du[:,-1]==+1]
Iun = I[Du[:,-1]==-1]
Iu_not = np.setdiff1d(I, Iu)

In [62]:
Iup

array([0, 1, 2])

In [28]:
D = np.zeros((Iu_not.size, Iu.size))
for j in np.arange(len(Iu_not)):
    for i in np.arange(len(Iu)):
        x1 = x[Iu_not[j],0]-x[Iu[i],0]
        x2 = x[Iu_not[j],1]-x[Iu[i],1]
        D[j,i] = round(np.sqrt(np.sum((x1**2)+(x2**2))), 3)
D

array([[1.414, 2.   , 1.   , 5.   , 2.828, 4.123, 5.   ],
       [2.   , 1.414, 1.   , 5.   , 4.243, 5.385, 5.385],
       [4.243, 4.472, 6.403, 1.   , 6.325, 5.   , 1.   ],
       [2.236, 3.606, 3.162, 5.099, 1.   , 2.   , 4.472],
       [4.123, 5.385, 6.   , 4.472, 3.606, 1.414, 3.162],
       [1.414, 2.828, 3.   , 4.123, 2.   , 2.236, 3.606]])

In [47]:
near_dist = np.argsort(D[:,Iu])
near_dist

array([[2, 0, 1, 4, 5, 3, 6],
       [2, 1, 0, 4, 3, 5, 6],
       [3, 6, 0, 1, 5, 4, 2],
       [4, 5, 0, 2, 1, 6, 3],
       [5, 6, 4, 0, 3, 1, 2],
       [0, 4, 5, 1, 2, 6, 3]])

In [52]:
K_ITEMS = 3
k = np.arange(K_ITEMS)
near_dist = near_dist[:,k]
near_dist

array([[2, 0, 1],
       [2, 1, 0],
       [3, 6, 0],
       [4, 5, 0],
       [5, 6, 4],
       [0, 4, 5]])

In [79]:
nearItem = {Iu_not[i]: near_dist[i,:] for i in np.arange(len(Iu_not))}
nearItem

{7: array([2, 0, 1]),
 8: array([2, 1, 0]),
 9: array([3, 6, 0]),
 10: array([4, 5, 0]),
 11: array([5, 6, 4]),
 12: array([0, 4, 5])}

In [83]:
for i in Iu_not:
    array = nearItem[i]
    positive = array[np.isin(array, Iup)]
    negative = array[np.isin(array, Iun)]
    score = np.nan
    if positive.size > negative.size:
        score = +1
    else:
        score = -1
    print('I{}+ = {}' .format(i, positive))
    print('I{}- = {}' .format(i, negative))
    print('predict1({}) = {:.3f}' .format(i, score))

        

I7+ = [2 0 1]
I7- = []
predict1(7) = 1.000
I8+ = [2 1 0]
I8- = []
predict1(8) = 1.000
I9+ = [0]
I9- = [3 6]
predict1(9) = -1.000
I10+ = [0]
I10- = [4 5]
predict1(10) = -1.000
I11+ = []
I11- = [5 6 4]
predict1(11) = -1.000
I12+ = [0]
I12- = [4 5]
predict1(12) = -1.000


In [93]:
pred_score = {}
for i in Iu_not:
    array = nearItem[i]
    positive = array[np.isin(array, Iup)]
    negative = array[np.isin(array, Iun)]
    score = round(((positive.size - negative.size) / K_ITEMS), 3)
    
    pred_score[i] = score
pred_score


{7: 1.0, 8: 1.0, 9: -0.333, 10: -0.333, 11: -1.0, 12: -0.333}

In [94]:
# 上位K件
TOP_K = 3
# しきい値
THETA = 0
rec_list = 
rec_list = sorted(pred_score.items(), key=lambda x:x[1], reverse=True)
rec_list

NameError: name 'TOP_K' is not defined

In [99]:
keys = [k for k, t in pred_score.items() if t > 0]
rec_list = {keys[i]: pred_score[keys[i]] for i in np.arange(len(keys))}
rec_list

{7: 1.0, 8: 1.0}